[versions]
androidGradlePlugin = "7.4.2"
androidxComposeMaterial3 = "1.1.0-alpha06"
detekt = "1.22.0"
junit5 = "5.8.2"
kotlin = "1.8.10"
lifecycleRuntimeKtx = "2.5.1"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.6.1" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2023.01.00" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.9.0" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.5.1" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version = "1.1.5" }
junit4 = { group = "junit", name = "junit", version = "4.13.2" }
junit5-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit5-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }

detekt-plugins-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
junit5 = { id = "de.mannodermaus.android-junit5", version = "1.8.2.1" }
kotlin-android = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }