name: CI - verify Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Verify code correctness
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Init gradle
        run: ./gradlew init
      - name: Detekt
        run: ./gradlew detekt
      - name: Assemble
        run: ./gradlew assembleDebug
      - name: Test
        run: ./gradlew testDebugUntiTest
